pool:
  vmImage: windows-latest

strategy:
  matrix:
    'Flutter 3.19.6':
      version: '3.19.6'

steps:
  - checkout: self
    submodules: recursive

  - task: FlutterInstall@0
    inputs:
      mode: auto
      channel: stable
      version: 'custom'
      customVersion: '$(version)'

  - task: FlutterBuild@0
    inputs:
      target: 'windows'
      projectDirectory: '.'
      debugMode: true
    displayName: 'Build Desktop on Windows'
