variables:
  executable_name: 'accounts_lister'
  artifact_name: 'Accounts Lister'

stages:
  - stage: 'WindowsAndroidStage'
    displayName: 'Windows & Android Build Stage'
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: 'WindowsAndroidJob'
        displayName: 'Windows & Android Build Job'
        steps:
          - template: AzurePipelineTemplates/recursive-submodule-checkout.yml
          - template: AzurePipelineTemplates/flutter_install.yml
          - template: AzurePipelineTemplates/build_windows.yml
            parameters:
              executable_name: $(executable_name)
              artifact_name: $(artifact_name)
          - template: AzurePipelineTemplates/build_android.yml
            parameters:
              artifact_name: $(artifact_name)

  - stage: 'macOSiOSStage'
    displayName: 'macOS & iOS Build Stage'
    pool:
      vmImage: 'macos-latest'
    jobs:
      - job: 'macOSiOSJob'
        displayName: 'macOS & iOS Build Job'
        steps:
          - template: AzurePipelineTemplates/recursive-submodule-checkout.yml
          - template: AzurePipelineTemplates/flutter_install.yml
          - template: AzurePipelineTemplates/build_macos.yml
            parameters:
              executable_name: $(executable_name)
              artifact_name: $(artifact_name)
          - template: AzurePipelineTemplates/build_ios.yml
            parameters:
              artifact_name: $(artifact_name)

  - stage: 'LinuxStage'
    displayName: 'Linux Build Stage'
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: 'LinuxJob'
        displayName: 'Linux Build Job'
        steps:
          - template: AzurePipelineTemplates/recursive-submodule-checkout.yml
          - template: AzurePipelineTemplates/flutter_install.yml
          - template: AzurePipelineTemplates/build_linux.yml
            parameters:
              executable_name: $(executable_name)
              artifact_name: $(artifact_name)
