name: accounts_lister
description: Accounts Lister for Account Ledger

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-171.0.dev <4.0.0"

dependencies:
  advanced_datatable: ^0.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.0.0
  account_ledger_library:
    path: account_ledger_library_dart
  integer: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
